2016-08-16 22:22:36.959 [debug] <0.54.0>@lager_handler_watcher:94 Lager installed handler {lager_file_backend,
                            "/root/bin/basho_bench/tests/20160816_222236/error.log"} into lager_event
2016-08-16 22:22:36.959 [debug] <0.56.0>@lager_handler_watcher:94 Lager installed handler {lager_file_backend,
                            "/root/bin/basho_bench/tests/20160816_222236/console.log"} into lager_event
2016-08-16 22:22:36.959 [debug] <0.58.0>@lager_handler_watcher:94 Lager installed handler error_logger_lager_h into error_logger
2016-08-16 22:22:36.989 [debug] <0.41.0> Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.60.0>
2016-08-16 22:22:36.989 [debug] <0.40.0> Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.61.0>
2016-08-16 22:22:36.990 [debug] <0.42.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.62.0>
2016-08-16 22:22:36.990 [debug] <0.42.0> Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0}]) at pid <0.63.0>
2016-08-16 22:22:37.438 [debug] <0.50.0>@lager_handler_watcher:94 Lager installed handler lager_backend_throttle into lager_event
2016-08-16 22:22:37.521 [info] <0.7.0> Application lager started on node nonode@nohost
2016-08-16 22:22:37.521 [notice] <0.47.0>@lager_file_backend:127 Changed loglevel of /root/bin/basho_bench/tests/20160816_222236/console.log to debug
2016-08-16 22:22:37.532 [info] <0.2.0>@basho_bench:log_dimensions:253 Est. data size: 9.54 MB
2016-08-16 22:22:37.588 [debug] <0.72.0> Supervisor sasl_safe_sup started alarm_handler:start_link() at pid <0.73.0>
2016-08-16 22:22:37.588 [debug] <0.72.0> Supervisor sasl_safe_sup started overload:start_link() at pid <0.74.0>
2016-08-16 22:22:37.589 [debug] <0.71.0> Supervisor sasl_sup started supervisor:start_link({local,sasl_safe_sup}, sasl, safe) at pid <0.72.0>
2016-08-16 22:22:37.599 [debug] <0.71.0> Supervisor sasl_sup started release_handler:start_link() at pid <0.75.0>
2016-08-16 22:22:37.599 [info] <0.7.0> Application sasl started on node nonode@nohost
2016-08-16 22:22:37.647 [debug] <0.80.0> Supervisor crypto_sup started crypto_server:start_link() at pid <0.81.0>
2016-08-16 22:22:37.648 [info] <0.7.0> Application crypto started on node nonode@nohost
2016-08-16 22:22:37.672 [debug] <0.90.0> Supervisor folsom_sup started folsom_sample_slide_sup:start_link() at pid <0.91.0>
2016-08-16 22:22:37.676 [debug] <0.90.0> Supervisor folsom_sup started folsom_meter_timer_server:start_link() at pid <0.92.0>
2016-08-16 22:22:37.680 [debug] <0.90.0> Supervisor folsom_sup started folsom_metrics_histogram_ets:start_link() at pid <0.93.0>
2016-08-16 22:22:37.680 [info] <0.7.0> Application folsom started on node nonode@nohost
2016-08-16 22:22:37.715 [info] <0.86.0>@basho_bench_stats_writer_csv:new:43 module=basho_bench_stats_writer_csv event=start stats_sink=csv
2016-08-16 22:22:37.715 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_stats:start_link() at pid <0.86.0>
2016-08-16 22:22:37.721 [info] <0.95.0>@basho_bench_valgen:init_source:88 Random source: calling crypto:rand_bytes(100663296) (override with the 'value_generator_source_size' config option
2016-08-16 22:22:39.988 [info] <0.95.0>@basho_bench_valgen:init_source:95 Random source: finished crypto:rand_bytes(100663296)
2016-08-16 22:22:40.007 [info] <0.97.0>@basho_bench_driver_redis:new:51 Using target "127.0.0.1":6379 for worker 1
2016-08-16 22:22:40.008 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_1, 1) at pid <0.95.0>
2016-08-16 22:22:40.011 [info] <0.99.0>@basho_bench_driver_redis:new:51 Using target "127.0.0.1":6379 for worker 2
2016-08-16 22:22:40.012 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_2, 2) at pid <0.98.0>
2016-08-16 22:22:40.015 [info] <0.101.0>@basho_bench_driver_redis:new:51 Using target "127.0.0.1":6379 for worker 3
2016-08-16 22:22:40.015 [debug] <0.85.0> Supervisor basho_bench_sup started basho_bench_worker:start_link(basho_bench_worker_3, 3) at pid <0.100.0>
2016-08-16 22:22:40.016 [debug] <0.26.0> Supervisor kernel_safe_sup started timer:start_link() at pid <0.102.0>
2016-08-16 22:22:40.026 [info] <0.101.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.101.0> on nonode@nohost
2016-08-16 22:22:40.026 [info] <0.99.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.99.0> on nonode@nohost
2016-08-16 22:22:40.027 [info] <0.97.0>@basho_bench_worker:worker_idle_loop:237 Starting max worker: <0.97.0> on nonode@nohost
2016-08-16 22:22:40.027 [info] <0.7.0> Application basho_bench started on node nonode@nohost
2016-08-16 22:22:40.055 [debug] <0.106.0> Supervisor inet_gethost_native_sup started undefined at pid <0.107.0>
2016-08-16 22:22:40.055 [debug] <0.26.0> Supervisor kernel_safe_sup started inet_gethost_native:start_link() at pid <0.106.0>
2016-08-16 22:22:53.300 [error] <0.11053.1> CRASH REPORT Process <0.11053.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:22:54.023 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:22:58.587 [error] <0.29713.1> CRASH REPORT Process <0.29713.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:22:58.867 [error] <0.30926.1> CRASH REPORT Process <0.30926.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:22:59.022 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},2},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},2}]
2016-08-16 22:22:59.075 [error] <0.31701.1> CRASH REPORT Process <0.31701.1> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:00.023 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:02.273 [error] <0.10918.2> CRASH REPORT Process <0.10918.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:02.515 [error] <0.12065.2> CRASH REPORT Process <0.12065.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:02.526 [error] <0.12117.2> CRASH REPORT Process <0.12117.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:03.024 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},3},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},3}]
2016-08-16 22:23:05.675 [error] <0.24446.2> CRASH REPORT Process <0.24446.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:06.023 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:07.108 [error] <0.29769.2> CRASH REPORT Process <0.29769.2> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:08.022 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:09.089 [error] <0.4675.3> CRASH REPORT Process <0.4675.3> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:10.023 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:13.057 [error] <0.19470.3> CRASH REPORT Process <0.19470.3> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:14.021 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:18.037 [error] <0.3880.4> CRASH REPORT Process <0.3880.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:19.022 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:21.034 [error] <0.14002.4> CRASH REPORT Process <0.14002.4> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:22.023 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:30.315 [error] <0.12724.5> CRASH REPORT Process <0.12724.5> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:31.022 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:33.032 [error] <0.22211.5> CRASH REPORT Process <0.22211.5> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:34.021 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:36.125 [error] <0.303.6> CRASH REPORT Process <0.303.6> with 0 neighbours exited with reason: {connection_error,{connection_error,eaddrnotavail}} in gen_server:init_it/6 line 320
2016-08-16 22:23:37.022 [info] <0.86.0>@basho_bench_stats:process_stats:265 Errors:[{{get,get},1},{{{get,get},{connection_error,{connection_error,eaddrnotavail}}},1}]
2016-08-16 22:23:41.033 [info] <0.86.0>@basho_bench_stats:report_total_errors:294 Total Errors:
2016-08-16 22:23:41.033 [info] <0.86.0>@basho_bench_stats:report_total_errors:300   {{get,get},{connection_error,{connection_error,eaddrnotavail}}}: 16
2016-08-16 22:23:41.033 [info] <0.86.0>@basho_bench_stats_writer_csv:terminate:62 module=basho_bench_stats_writer_csv event=stop stats_sink=csv
